#!/usr/bin/env bash

# One of the following: xrandr, xbacklight, kernel
METHOD="xbacklight"

URGENT_VALUE=10


get_brightness () {
    if [[ "${METHOD}" = "xrandr" ]]; then
        device="${BLOCK_INSTANCE:-primary}"
        xrandrOutput=$(xrandr --verbose)

        if [[ "${device}" = "primary" ]]; then
            device=$(echo "${xrandrOutput}" | grep 'primary' | head -n 1 | awk -F ' ' '{print $1}')
        fi

        curBrightness=$(echo "${xrandrOutput}" | grep "${device}" -A 5 | grep -i "Brightness" | awk -F ':' '{print $2}')
    elif [[ "${METHOD}" = "kernel" ]]; then
        device="${BLOCK_INSTANCE:-intel_backlight}"
        maxBrightness=$(cat /sys/class/backlight/${device}/max_brightness)
        curBrightness=$(cat /sys/class/backlight/${device}/brightness)
    elif [[ "${METHOD}" = "xbacklight" ]]; then
	curBrightness=$(printf "%.0f" $(xbacklight -get) )
    fi
    if [[ "${curBrightness}" -le 0 ]]; then
        exit
    fi

    if [[ "${METHOD}" = "xrandr" ]]; then
        percent=$(echo "scale=0;${curBrightness} * 100" | bc -l)
    elif [[ "${METHOD}" = "kernel" ]]; then
        percent=$(echo "scale=0;${curBrightness} / ${maxBrightness} * 100" | bc -l)
    elif [[ "${METHOD}" = "xbacklight" ]]; then
        percent=$(echo "scale=0;${curBrightness}" | bc -l)
    fi

    return $percent
}

get_brightness
percent=$?

# scrolls
if [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  xbacklight -inc 5
elif [[ "${BLOCK_BUTTON}" -eq 4 ]] && [[ $percent -ge $URGENT_VALUE ]]; then
  xbacklight -dec 5
fi

# clicks
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  xbacklight -set 100
elif [[ "${BLOCK_BUTTON}" -eq 3 ]] && [[ $percent -ge $URGENT_VALUE ]]; then
  xbacklight -set 5
fi

get_brightness
percent=$?
percent=${percent%.*}

if [[ "${percent}" -le 0 ]]; then
  exit
fi

echo "BRT ${percent}%"
echo "BRT ${percent}%"
echo ""

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
