#!/usr/bin/env bash

ip a l wg-home >/dev/null 2>/dev/null
if [ $? -eq 0 ]
then
    echo "WG: Home"
    echo "WG: Home"
    echo "#00FF00"
    CLICK_CMD="systemctl stop wg-quick-wg-home.service"
else
    echo "WG"
    echo "WG"
    echo "#888888"
    CLICK_CMD="systemctl start wg-quick-wg-home.service"
fi

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    $CLICK_CMD
fi

exit 0
